apiVersion: kuma.io/v1alpha1
kind: HealthCheck
metadata:
  name: frontend-to-backend
  namespace: kong-mesh-demo
mesh: default
spec:
  sources:
  - match:
      kuma.io/service: frontend_kong-mesh-demo_svc_8080
  destinations:
  - match:
      kuma.io/service: backend_kong-mesh-demo_svc_3001
  conf:
    interval: 10s
    timeout: 2s
    unhealthyThreshold: 3
    healthyThreshold: 1
