apiVersion: kuma.io/v1alpha1
kind: FaultInjection
mesh: default
metadata:
  name: abort
spec:
  sources:
    - match:
        kuma.io/service: frontend_kong-mesh-demo_svc_8080
        kuma.io/protocol: http
  destinations:
    - match:
        kuma.io/service: backend_kong-mesh-demo_svc_3001
        kuma.io/protocol: http
  conf:        
    abort:
      httpStatus: 503
      percentage: 100
