apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuma-policy-management
rules:
- apiGroups:
  - kuma.io
  resources:
  - trafficpermissions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuma-policy-management-backend-owner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuma-policy-management
subjects:
- kind: User
  name: backend-owner
  apiGroup: rbac.authorization.k8s.io
