apiVersion: kuma.io/v1alpha1
kind: AccessRole
metadata:
  name: backend-owner
spec:
  rules:
  - types: ["TrafficPermission"]
    mesh: default
    access: ["CREATE", "UPDATE", "DELETE"]
    when:
    - destinations:
        match:
          kuma.io/service: backend_kong-mesh-demo_svc_3001
---
apiVersion: kuma.io/v1alpha1
kind: AccessRoleBinding
metadata:
  name: backend-owners
spec:
  subjects:
  - type: User
    name: backend-owner
  roles:
  - backend-owner
