apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: marketplace
  namespace: kong
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 8080
