apiVersion: kuma.io/v1alpha1
kind: FaultInjection
metadata:
  name: fi-backendv1
  namespace: kong-mesh-demo
mesh: default
spec:
  sources:
  - match:
      kuma.io/service: frontend_kong-mesh-demo_svc_8080
  destinations:
  - match:
      kuma.io/service: backend_kong-mesh-demo_svc_3001
      kuma.io/protocol: http
      version: v0
  conf:
    abort:
      httpStatus: 500
      percentage: 100
    delay:
      percentage: 50.5
      value: 5s
    responseBandwidth:
      limit: 50 mbps
      percentage: 50 
