apiVersion: kuma.io/v1alpha1
kind: CircuitBreaker
mesh: default
metadata:
  name: circuit-breaker-example
spec:
  sources:
  - match:
      kuma.io/service: frontend_kong-mesh-demo_svc_8080
  destinations:
  - match:
      kuma.io/service: backend_kong-mesh-demo_svc_3001
  conf:
    interval: 5s
    baseEjectionTime: 90s
    maxEjectionPercent: 100
    splitExternalAndLocalErrors: false 
    thresholds:
      maxConnections: 2
      maxPendingRequests: 2
      maxRequests: 2
      maxRetries: 2
    detectors:
      totalErrors: 
        consecutive: 2
      gatewayErrors: 
        consecutive: 2
      localErrors: 
        consecutive: 2
      standardDeviation:
        requestVolume: 10
        minimumHosts: 5
        factor: 1.9
      failure:
        requestVolume: 10
        minimumHosts: 5
        threshold: 85
