apiVersion: v1
kind: Namespace
metadata:
  name: kongmesh-corp
  namespace: kongmesh-corp
  annotations:
    kuma.io/sidecar-injection: enabled
    kuma.io/mesh: corporate-ins
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kongmesh-corp
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "redis"
          ports:
            - name: tcp
              containerPort: 6379
          lifecycle:
            postStart:
              exec:
                command: ["/usr/local/bin/redis-cli", "set", "zone", "local"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kongmesh-corp
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
  namespace: kongmesh-corp
spec:
  selector:
    matchLabels:
      app: counter-app
  replicas: 1
  template:
    metadata:
      labels:
        app: counter-app
        version: v1
    spec:
      containers:
        - name: counter-app
          image: "thefosk/kuma-demo"
          env:
            - name: REDIS_HOST
              value: "redis.kongmesh-corp.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: APP_VERSION
              value: "1.0"
            - name: APP_COLOR
              value: "#efefef"
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app-v2
  namespace: kongmesh-corp
spec:
  selector:
    matchLabels:
      app: counter-app
  replicas: 1
  template:
    metadata:
      labels:
        app: counter-app
        version: v2
    spec:
      containers:
        - name: counter-app
          image: "thefosk/kuma-demo"
          env:
            - name: REDIS_HOST
              value: "redis.kongmesh-corp.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: APP_VERSION
              value: "2.0"
            - name: APP_COLOR
              value: "#5da36f"
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: counter-app
  namespace: kongmesh-corp
  annotations:
    5000.service.kuma.io/protocol: http
    ingress.kubernetes.io/service-upstream: "true"
spec:
  selector:
    app: counter-app
  ports:
  - protocol: TCP
    port: 5000
